[package]
name = "stardawn"
version = "0.1.0"
edition = "2021"


[dependencies]
mathio = "0.2.1"
bevy = { version = "0.11.2", features = ["dynamic_linking"] }
bevy_lunex = "0.0.6"
bevy_vector_shapes = "0.5.1"
